In [2]:
import sympy
from sympy import *
import numpy as np

In [3]:
x,y = sympy.symbols('x,y', real=True)
f1 = -y
f2 = x - 3*y*(1-x**2)


In [4]:
f1

-y

In [5]:
F = sympy.Matrix([f1,f2])
F.jacobian([x,y])

Matrix([
[        0,         -1],
[6*x*y + 1, 3*x**2 - 3]])

In [6]:
F.jacobian([x,y]).subs([(x,0), (y,0)])

Matrix([
[0, -1],
[1, -3]])

In [12]:
xx = MatrixSymbol("xx", 2, 1)
xx

xx

In [9]:
W = np.array([[1,2],[3,1]], dtype=float) # shape (2,2)
V = np.array([[1,-1]], dtype=float) # shape (1,2)

print(W)
print(V)

[[1. 2.]
 [3. 1.]]
[[ 1. -1.]]


In [10]:
W @ xx

array([[1.0*xx[0, 0] + 2.0*xx[1, 0]],
       [3.0*xx[0, 0] + 1.0*xx[1, 0]]], dtype=object)

In [17]:
from sympy.functions import exp
1/(1+exp(- W @ xx))

(1 + exp([[-1.0*xx[0, 0] - 2.0*xx[1, 0]], [-3.0*xx[0, 0] - 1.0*xx[1, 0]]]))**(-1)

In [18]:
from sympy.functions import exp

# The sigmoid = logistic function.
def sigmoid(x):
    return 1/(1+exp(-x))

# Forward application of the neural network; returns the prediction.
def forward(xx, W, V):
    hh = W @ xx         # shape (2,)
    aa = sigmoid(hh)    # shape (2,)
    y = V @ aa          # shape (1,)
    
    return y

In [19]:
forward(xx, W, V)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)